# Generated by Django 4.1.7 on 2023-03-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя человека')),
                ('picture', models.ImageField(upload_to='', verbose_name='Фото человека')),
                ('is_enter', models.BooleanField(verbose_name='Внутри ли человек')),
            ],
            options={
                'verbose_name': 'известный человек',
                'verbose_name_plural': 'известные люди',
            },
        ),
        migrations.CreateModel(
            name='UnknownEnterPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='', verbose_name='Фото человека')),
            ],
            options={
                'verbose_name': 'неизвестный человек',
                'verbose_name_plural': 'неизвестные люди',
            },
        ),
    ]
