# Generated by Django 4.1.7 on 2023-03-10 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_unknownenterperson_last_enter'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_exit',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 3, 10, 14, 10, 3, 320880, tzinfo=datetime.timezone.utc), verbose_name='Последний выход человека'),
        ),
        migrations.AddField(
            model_name='unknownenterperson',
            name='last_exit',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 3, 10, 14, 10, 3, 321069, tzinfo=datetime.timezone.utc), verbose_name='Последний выход человека'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_enter',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 3, 10, 14, 10, 3, 320642, tzinfo=datetime.timezone.utc), verbose_name='Последний вход человека'),
        ),
        migrations.AlterField(
            model_name='unknownenterperson',
            name='last_enter',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 3, 10, 14, 10, 3, 321057, tzinfo=datetime.timezone.utc), verbose_name='Последний вход человека'),
        ),
    ]
