# Generated by Django 4.1.7 on 2023-03-10 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_person_last_exit_unknownenterperson_last_exit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_enter',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Последний вход человека'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_exit',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Последний выход человека'),
        ),
        migrations.AlterField(
            model_name='unknownenterperson',
            name='last_enter',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Последний вход человека'),
        ),
        migrations.AlterField(
            model_name='unknownenterperson',
            name='last_exit',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Последний выход человека'),
        ),
    ]
