# Generated by Django 4.1.7 on 2023-04-03 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_person_last_enter_alter_person_last_exit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('data_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Последний выход человека')),
                ('image', models.ImageField(upload_to='history/', verbose_name='Фото человека')),
            ],
        ),
    ]
