# Generated by Django 4.1.7 on 2023-04-03 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'История входа/выхода', 'verbose_name_plural': 'Истории входа/выхода'},
        ),
    ]
