# Generated by Django 4.1.7 on 2023-04-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_history_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotAdmins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя человека')),
                ('telegram_id', models.IntegerField(verbose_name='ID в Telegram')),
            ],
            options={
                'verbose_name': 'Админ Telegram',
                'verbose_name_plural': 'Админ Telegram',
            },
        ),
    ]
