# Generated by Django 4.1.7 on 2023-04-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_telegrambotadmins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='image',
            field=models.ImageField(blank=True, upload_to='history/', verbose_name='Фото человека'),
        ),
    ]
