# Generated by Django 4.1.7 on 2023-10-18 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_history_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='', verbose_name='Фото человека')),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Последний вход человека')),
            ],
        ),
    ]
