# Generated by Django 4.1.7 on 2024-04-14 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_templateperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_food_conected',
            field=models.BooleanField(default=False, verbose_name='Питается ли человек в столовой'),
        ),
        migrations.AddField(
            model_name='person',
            name='last_eat',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Последний приём пищи'),
        ),
    ]
