# Generated by Django 4.1.7 on 2024-09-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_person_is_food_conected_person_last_eat'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('secret_key', models.CharField(default='ct3iiic1', max_length=100, verbose_name='Секретный ключ камеры')),
            ],
            options={
                'verbose_name': 'Камера на вход',
                'verbose_name_plural': 'Камеры на вход',
            },
        ),
        migrations.CreateModel(
            name='ExitCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('secret_key', models.CharField(default='7eziyq7z', max_length=100, verbose_name='Секретный ключ камеры')),
            ],
            options={
                'verbose_name': 'Камера на выход',
                'verbose_name_plural': 'Камеры на выход',
            },
        ),
    ]
