# Generated by Django 4.1.7 on 2024-09-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_entercamera_exitcamera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entercamera',
            name='secret_key',
            field=models.CharField(default='nty679u5', max_length=100, verbose_name='Секретный ключ камеры'),
        ),
        migrations.AlterField(
            model_name='exitcamera',
            name='secret_key',
            field=models.CharField(default='bc5vefzf', max_length=100, verbose_name='Секретный ключ камеры'),
        ),
    ]
