# Generated by Django 4.1.7 on 2024-09-20 15:34

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_entercamera_secret_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя сотрудника')),
                ('picture', models.ImageField(upload_to='', verbose_name='Фото сотрудника')),
                ('is_enter', models.BooleanField(verbose_name='Внутри ли сотрудник')),
                ('access_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Уровень доступа')),
                ('last_enter', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Последний вход сотрудника')),
                ('last_exit', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Последний выход сотрудника')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя ученика')),
                ('picture', models.ImageField(upload_to='', verbose_name='Фото ученика')),
                ('is_enter', models.BooleanField(verbose_name='Внутри ли ученик')),
                ('is_food_conected', models.BooleanField(default=False, verbose_name='Питается ли ученик в столовой')),
                ('last_eat', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Последний приём пищи')),
                ('last_enter', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Последний вход ученика')),
                ('last_exit', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Последний выход ученика')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='entercamera',
            name='secret_key',
            field=models.CharField(default='80dbo5em', max_length=100, verbose_name='Секретный ключ камеры'),
        ),
        migrations.AlterField(
            model_name='exitcamera',
            name='secret_key',
            field=models.CharField(default='qado9n83', max_length=100, verbose_name='Секретный ключ камеры'),
        ),
    ]
