# Generated by Django 4.1.7 on 2024-09-20 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_closedroom_alter_entercamera_secret_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedroom',
            name='access_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Мин. уровень доступа'),
        ),
        migrations.AlterField(
            model_name='entercamera',
            name='secret_key',
            field=models.CharField(max_length=100, verbose_name='Секретный ключ камеры'),
        ),
    ]
