# Generated by Django 4.1.7 on 2024-09-20 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_closedroom_access_level_alter_entercamera_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedroom',
            name='last_enter',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Последний вход в комнату'),
        ),
    ]
