# Generated by Django 4.1.7 on 2024-09-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_closedroom_last_enter'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='history_type',
            field=models.CharField(choices=[('known_enter', 'Известный вошёл'), ('known_exit', 'Известный вышел'), ('unknown_enter', 'Неизвестный вошёл'), ('unknown_exit', 'Неизвестный вышел'), ('open_room', 'Открытие комнаты'), ('clear_enter', 'Очистка входящих'), ('another', 'Другое')], default='another', max_length=100, verbose_name='Тип истории'),
        ),
    ]
