# Generated by Django 4.1.7 on 2024-10-20 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_history_history_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='RoomCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=100, verbose_name='Секретный ключ камеры')),
                ('to_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='api.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Камера в комнате',
                'verbose_name_plural': 'Камеры в комнатах',
            },
        ),
        migrations.CreateModel(
            name='RoomAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=100, verbose_name='Секретный ключ устройства')),
                ('to_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='api.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Микрофон в комнате',
                'verbose_name_plural': 'Микрофоны в комнатах',
            },
        ),
    ]
