# Generated by Django 4.1.7 on 2024-10-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_closedroom_secret_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="voice_profile",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
